### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by molpopgen** [conda-forge/cythongsl-feedstock#2]
I've had some CI failures due to cythongsl not being available for Py3.6, which is what the current miniconda distro is based on.

~~~
conda search -c conda-forge cythongsl
Fetching package metadata ...........
cythongsl                    0.2.1                    py35_0  conda-forge     
                             0.2.1                    py27_0  conda-forge     
                             0.2.1                    py34_0  conda-forge  
~~~

I've looked at the recipe/meta.yaml, but that doesn't seem to specify python versions.  Any chance of getting this package updated?

**Comment by ocefpaf** [comment]
You need to check the build [matrix](https://github.com/conda-forge/cythongsl-feedstock/blob/master/.travis.yml#L12-L14) to get that information. Re-rendering the feedstock with `conda-smithy` should do the trick to update it to the latest build matrix.

I am doing this now, but if you are familiar with `conda-smithy` and/or is willing to help maintain this feedstock let me know and I can give you some directions on how to do it yourself.

**Comment by molpopgen** [comment]
Thanks.  I wasn't sure if that file should be touched, given the comments
at the top re: it being auto-generated.

**Comment by ocefpaf** [comment]
> Thanks.  I wasn't sure if that file should be touched, given the comments
at the top re: it being auto-generated.

You are correct. `conda-smithy` is the tool to re-generate it. Here is what I did in #3 

```shell
conda install conda-smithy -c conda-forge
conda smithy rerender  # from the feedstock root directory
...send the changes in a PR...
```

**Comment by molpopgen** [comment]
Thanks.
